### ISSUE TITLE
HotReload connection Issue

### ISSUE THREAD

**Issue by yurkinh** [adospace/reactorui-xamarin#1]
Hi
When I try to use HotReload on android emulator or device I'm always getting connection error:

**Sending to emulator...
System.Net.Sockets.SocketException (0x80004005): No connection could be made because the target machine actively refused it 127.0.0.1:45820
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.Net.Sockets.TcpClient.Connect(IPEndPoint remoteEP)
   at System.Net.Sockets.TcpClient.Connect(IPAddress address, Int32 port)
   at XamarinReactorUI.HotReloadVsExtension.ReloadCommand.SendAssemblyToEmulator(String assemblyPath, IVsOutputWindowPane outputPane)Building**

**Comment by adospace** [comment]
Hi @yurkinh, right now hot reload functionality is somewhat rudimentary, so please make sure that following are true:
1) You are in debug mode
2) You have selected the Xamarin Forms project (that one that contains the component) as sometime just selecting another project in solution explorer cause it to change

Also I've written a small guide to troubleshoot hot reload issues, please take a look at https://adospace.gitbook.io/reactorui/hot-reload-trouble-shooting

**Comment by yurkinh** [comment]
Hi @adospace 
I've already read all the documentation and tried troubleshooting suggestions
But still no luck(

![error](https://user-images.githubusercontent.com/17849938/78764213-e73be300-798e-11ea-9c60-4c0bbb569da9.png)

**Comment by adospace** [comment]
ok I see the problem, you're selecting the Android project not the Xamarin Forms one; in fact hot reload is trying to build the ReactorUIHelloWork.Android.dll and not the  ReactorUIHelloWork.dll

**Comment by adospace** [comment]
Also please note that right now I've tested hot reload only with emulator. 
Said that there is no reason that prevents it to working fine with physical devices too; just ensure that you only have one system active at time, either the emulator or the physical device.

**Comment by adospace** [comment]
Latest version of the VS extension https://github.com/adospace/reactorui-xamarin/commit/64f3fc96710eb1a3754bcbe4a1a69145e55d5cd4 (just uploaded) automatically detect the XF project.
I'll close this issue for now, just re-open it if you find something new.
