### ISSUE TITLE
External DLL re injection on HotReload

### ISSUE THREAD

**Issue by Suprndm** [adospace/reactorui-xamarin#10]
Currently when i make changes on a project that xamarinForm project is referencing, hot reload does not seem to take notice of those changes. 

A use case is when I work in an hexagonal architecture and I change  model on another domain (i.e project). It would be a plus to also re inject the updated dlls on hot reloading.

Any plans for that ? Did I miss something ? Would it be too hard to make ?

Thanks

**Comment by adospace** [comment]
Yes, hot reload works only for the portable (xamarin forms) assembly and yes it would be too hard to reload satellite assemblies too and probably not required in most cases.
The main idea of the hot-reload module is to let developers compose components (i.e. views) directly while debugging and see any changes on the fly: domain models, DI services, etc should instead be tested separately thru unit tests.

**Comment by Suprndm** [comment]
I see. 

Well my case is I develop a UI/Game engine, as a lib, on a .net standard project. I then have a xamarin form project to test my engine. I wish i could benefit from Hotreload while developing the lib.

Maybe a trick like "add as link" or share namespace would make it work for my case ?.

**Comment by adospace** [comment]
yes, of course, if you add as link any source file from the external lib it will be compiled in the xamarin forms assembly thus will work
