### ISSUE TITLE
Has the IValueSet interface been changed?

### ISSUE THREAD

**Issue by saint4eva** [adospace/reactorui-xamarin#11]
I have been playing with ReactorUI - it is nice. However, I tried to create a component state and inherit IValueSet, but it is not available. And the SetState method is not available also - it is showing red squiggly

**Comment by adospace** [comment]
Yes it's now named IState

**Comment by saint4eva** [comment]
I inherited from IState, and tried to create the OnButtonClicked  method, but the SetState(s => s.Counter++) is still showing red squiggly and the app cannot compile

**Comment by adospace** [comment]
Can you post the code?

**Comment by saint4eva** [comment]
![image](https://user-images.githubusercontent.com/3264826/88915730-b7299000-d25c-11ea-961e-ef83ed3b40a1.png)


![image](https://user-images.githubusercontent.com/3264826/88915763-c3155200-d25c-11ea-9a5d-338aabf1affc.png)

And the SetState method is still squigllied.

**Comment by saint4eva** [comment]
`using System;
using Xamarin.Forms;
using XamarinReactorUI;

namespace XamReactorUIDemo
{
    public class MainComponentState : IState
    {
        public int Counter { get; set; }
    }

    public class MainComponent : RxComponent
    {
        private void OnButtonClicked()
        {
            SetState(s => s.Counter++);
        }

        public override VisualNode Render()
            => new RxNavigationPage()
            {
                new RxContentPage()
                {
                    new RxStackLayout()
                    {
                        new RxLabel("Hello World")
                        .TextColor(Color.Black).FontSize(NamedSize.Large),

                        new RxButton("Clicked Here")
                        .BackgroundColor(Color.Blue)
                        .CornerRadius(2)
                        .BorderColor(Color.Red)
                        .BorderWidth(3.0d)
                        .TextColor(Color.White),
                    }
                    .VCenter()
                    .HCenter()
                }
                .Title("Title World")
                .BackgroundColor(Color.LightGray)
            };
    }
}
`

**Comment by adospace** [comment]
MainComponent should derive from `RxComponent<MainComponentState>`: please take a look at the documentation https://adospace.gitbook.io/reactorui/guide/components-with-a-state

**Comment by saint4eva** [comment]
Thank you very much - that slipped through. 😄. I will continue playing with ReactorUI and once I am confident with it, I will start doing short-video series for other new app developers. 

Once more, thank you @adospace

**Comment by adospace** [comment]
You're welcome!
