### ISSUE TITLE
Will it continue to develop?

### ISSUE THREAD

**Issue by qcjxberin** [adospace/reactorui-xamarin#12]
Will it continue to develop?

**Comment by adospace** [comment]
Yes, I actively use this library in a work project so I'm surely going to fix bugs and improve perfomance.

Said that, Microsoft is clearly shifting over MAUI so I'm planning to upgrade it just to latest XF planned release (that is 5) when it will be out.

**Comment by Suprndm** [comment]
Hi,
Im heavily using reactorUI-xamarin for c# efficient hot reload. Thanks a lot by the way. I’m able to develop very efficiently with hot reload. When MAUI will be out, do you know if it will have native c# hot reload ? Do you plan to develop a dedicated lib for that plateform ?

**Comment by adospace** [comment]
Well, it's hard to say now but from what saw in the latest xamarin conf, MAUI will support MVU pattern with native hot-reload (MVU support will be in beta in the very first release in Nov 2021).

Regarding my library, it all depends on how c# hot-reload will work: for example, current XAML hot-reload deals only with XAML markup. If they implement a full hot reload (thru Comet) for c#, much like my library does, there will be no point in porting ReactorUI to MAUI.

Thanks for the interest!

**Comment by qcjxberin** [comment]
Is there a DEMO with icon in the input box
