### ISSUE TITLE
How to set On<iOS>().SetUseSafeArea(true); for RxContentPage or Component 

### ISSUE THREAD

**Issue by SarthakGz** [adospace/reactorui-xamarin#16]

**Comment by adospace** [comment]
I guess you mean (pseudo-code):
```
using Xamarin.Forms.PlatformConfiguration.iOSSpecific;

.Set(Page.UseSafeAreaProperty, true)
```

**Comment by SarthakGz** [comment]
> I guess you mean (pseudo-code):
> 
> ```
> using Xamarin.Forms.PlatformConfiguration.iOSSpecific;
> 
> .Set(Page.UseSafeAreaProperty, true)
> ```

Yes properties those does not have extension method
Thanks for the quick response

**Comment by SarthakGz** [comment]
I also couldn't set HasNavigationBar=false to RxNavigationPage
since no extension method for that

**Comment by adospace** [comment]
Please consider that reactorui for XF is going to be deprecated along with XF itself, if you're starting a new project please consider moving to MauiRector (https://github.com/adospace/reactorui-maui)

**Comment by SarthakGz** [comment]
I am just clearing my concept for reactor ui for now
and maui is not stable enough for me

**Comment by SarthakGz** [comment]
how to set properties which does not have extension methods
like HasNavigationBar=false of RxNavigationPage
