### ISSUE TITLE
Visual Studio for Mac support

### ISSUE THREAD

**Issue by yurkinh** [adospace/reactorui-xamarin#4]
Hi,
It would be very useful to add VS for Mac support for HotReload extension.
Are there any plans on that?

**Comment by adospace** [comment]
Unfortunately, I don't have a Mac (nor an iPhone) so at least for now I can't look at it; anyway I would be highly interested in accepting any PR.

Actually, the VS extension would be pretty easy to develop even for Mac (given that we have all the necessary packages).

In short, when you hit the hot reload button, these things happen in order:
1) Solution is built
2) If build succeed, find the right project (.net standard that references to ReactorUI and ReactorUI.Reload)
3) Send the assembly to the emulator/device with an adb connection (more or less is like sending a binary file via TCP)

**Comment by adospace** [comment]
I was able to create the extension for VS for Mac relatively easy and it seems working pretty well with both iOS and Android.
I'm going to publish more info on how to install it these days, so please stay tuned!

**Comment by yurkinh** [comment]
Great! Glad to hear that.

**Comment by adospace** [comment]
🎉 Hey, VS Mac support is out! please take a look at how to install the extension [here](https://adospace.gitbook.io/reactorui/guide/setting-up)!
