### ISSUE TITLE
hot updated error

### ISSUE THREAD

**Issue by qcjxberin** [adospace/reactorui-xamarin#6]
I used it in the vs 2019 preview, refer to writing Hello world, found that it can not be hot updated, also refer to the document for configuration

**Comment by qcjxberin** [comment]
![image](https://user-images.githubusercontent.com/5792218/82402905-2bdb9380-9a90-11ea-8307-dbb817722ee9.png)

**Comment by qcjxberin** [comment]
![image](https://user-images.githubusercontent.com/5792218/82403097-9c82b000-9a90-11ea-8425-b40a7cf1844f.png)

**Comment by adospace** [comment]
Sorry, but I can't understand the issue. Have you followed the getting started tutorial?https://adospace.gitbook.io/reactorui/guide/hello-world-sample

Also, can you confirm that when you click the hot reload button or press CTRL+F7 your app build fine? (please look at the output pane)

Finally, can you confirm you have the latest Visual Studio extension version (1.6 at moment)?

**Comment by qcjxberin** [comment]
I confirm that I have the latest Visual Studio extension version, I use the latest version of VS 2019 Preview

**Comment by adospace** [comment]
Please answer ALL the above questions. 
Furthermore, can you confirm only one device/emulator is running while you debug? (as described in the documentation).

Can you share the output pane content after you press CTRL+F7?

**Comment by qcjxberin** [comment]
Yes, and I have tested in real machine environment and simulation environment

**Comment by qcjxberin** [comment]
There is no response after pressing CTRL + F7, there will be a short pause when the button is pressed

**Comment by qcjxberin** [comment]
Can run normally, but it can't be hot updated

**Comment by adospace** [comment]
Sorry but it's hard to say what's going on: probably there is a problem with adb on your machine but I can't help much without more information

**Comment by qcjxberin** [comment]
Does it support the latest version of vs 2019 preview? I am using this version? Is it incompatible?

**Comment by adospace** [comment]
I'm closing this issue because I can't provide more help, please open a new ticket if you need further assistance, thanks

**Comment by adospace** [comment]
For those who have the same problem, I found that sometimes Visual Studio extension is unable to create a port forward with adb. In case I just ran the command `adb forward tcp:45820 tcp:45820` from the adb command prompt.
