### ISSUE TITLE
IValueSet Is Not Exist

### ISSUE THREAD

**Issue by qcjxberin** [adospace/reactorui-xamarin#7]
https://adospace.gitbook.io/reactorui/guide/components-with-a-state/component-lifecycle

![image](https://user-images.githubusercontent.com/5792218/82419851-86391c00-9ab1-11ea-9a87-ff45ce1e4669.png)

maby IState?

**Comment by adospace** [comment]
yes it's IState (IValueSet was the old name), I've fixed the documentation, thanks
